### ISSUE TITLE
Writing cursor invisible on purple text-background with dark-doriphore theme

### ISSUE THREAD

**Issue by alixturcq** [vincent-peugnet/wcms#314]
With the dark doriphore theme enabled, the text vertical bar cursor is almost invisible when writing on a purple backgrounded text 
%HEADER?id=example%, it sometime makes it difficult to navigate through these texts

Minor minor issue

**Comment by vincent-peugnet** [comment]
It seems that background color of codeMirror can be configured using this:

```css
.CodeMirror-selected {background-color: var(--outline-background-color) !important;}
```

But the problem is that W's keyword syntax highlight is upon selection color.
